name: David B Nelson
favicon: null
layout_spectrum: 0.75196
typography_spectrum: 0.25346
title: David B Nelson
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.09033628040924668
  lightness: 0.7655388447456062
  saturation: 0.6178615365643054
  rhythmicContrast: 0.34888071240857244
purpose: []
