name: David B Nelson
favicon: null
layout_spectrum: 0
typography_spectrum: 0.25346
title: David B Nelson
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-74942020-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f5f5f7'
    - '#1e5082'
    - '#4c91b0'
    - '#95ced5'
    - '#706959'
  brandStrength: 0.09033628040924668
  lightness: 0.7655388447456062
  saturation: 0.6178615365643054
  rhythmicContrast: 0.34888071240857244
purpose: []
